FROM n4zim/minimal-php-projects:php

MAINTAINER Nazim Lachter <nlachter@gmail.com>

# Adding Symfony CLI
RUN curl -LsS https://symfony.com/installer -o /usr/local/bin/symfony \
 && chmod a+x /usr/local/bin/symfony
