version: '2'
services:
  web:
    image: n4zim/images:webissues1.1.5
    container_name: webissues-web
    ports:
      - 8001:80
    environment:
      DISPLAY_TYPES: "no"
    volumes:
      - ./data/web:/var/www/html/data # Only data files
      #- ./1.1.5:/var/www/html # Sync latest files
    links:
      - db:mysql
  db:
    image: mysql
    container_name: webissues-db
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: webissues
      MYSQL_PASSWORD: webissues
      MYSQL_DATABASE: webissues
