FROM n4zim/php-projects:fpm

MAINTAINER Nazim Lachter <nlachter@gmail.com>

# Adding Symfony CLI
RUN curl -LsS https://symfony.com/installer -o /usr/local/bin/symfony \
 && chmod a+x /usr/local/bin/symfony
